### ISSUE TITLE
Duplicate key errors when used with grails 4

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-charts-plugin#7]
```


For more details see https://docs.gradle.org/5.6.4/release-notes.html

ALAChart.unminified.js:531: ERROR - [JSC_DUPLICATE_OBJECT_KEY] Object literal contains illegal duplicate key "error", disallowed in strict mode
  531|             error: function(data) {
                   ^^^^^

ALAChart.unminified.js:1032: ERROR - [JSC_DUPLICATE_OBJECT_KEY] Object literal contains illegal duplicate key "error", disallowed in strict mode
  1032|             error: function(data) {
                    ^^^^^

2 error(s), 0 warning(s)
Closure uglify JS Exception
asset.pipeline.processors.MinifyException: [JSC_DUPLICATE_OBJECT_KEY. Object literal contains illegal duplicate key "error", disallowed in strict mode at ALAChart.unminified.js line 531 : 12, JSC_DUPLICATE_OBJECT_KEY. Object literal contains illegal duplicate key "error", disallowed in strict mode at ALAChart.unminified.js line 1032 : 12]
        at asset.pipeline.processors.ClosureCompilerProcessor.process(ClosureCompilerProcessor.groovy:80)
        at asset.pipeline.processors.ClosureCompilerProcessor$process$4.call(Unknown Source)
        at asset.pipeline.AssetCompiler$_compile_closure4.doCall(AssetCompiler.groovy:171)
        at sun.reflect.GeneratedMethodAccessor393.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
> Task :assetCompile FAILED
```

**Comment by djtfmartin** [comment]
Fixed in 2.1.1
